//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 礼物 的本地化字符串。
        /// </summary>
        internal static string gift_ {
            get {
                return ResourceManager.GetString("gift_", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 玫瑰 的本地化字符串。
        /// </summary>
        internal static string gift_300 {
            get {
                return ResourceManager.GetString("gift_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 铃铛 的本地化字符串。
        /// </summary>
        internal static string gift_325 {
            get {
                return ResourceManager.GetString("gift_325", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 星星 的本地化字符串。
        /// </summary>
        internal static string gift_376 {
            get {
                return ResourceManager.GetString("gift_376", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主播 的本地化字符串。
        /// </summary>
        internal static string lbl_anchor {
            get {
                return ResourceManager.GetString("lbl_anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 铃铛 的本地化字符串。
        /// </summary>
        internal static string lbl_ball {
            get {
                return ResourceManager.GetString("lbl_ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 富豪 的本地化字符串。
        /// </summary>
        internal static string lbl_bet {
            get {
                return ResourceManager.GetString("lbl_bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 喵粮 的本地化字符串。
        /// </summary>
        internal static string lbl_catfood {
            get {
                return ResourceManager.GetString("lbl_catfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 富豪 的本地化字符串。
        /// </summary>
        internal static string lbl_consume {
            get {
                return ResourceManager.GetString("lbl_consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 家族 的本地化字符串。
        /// </summary>
        internal static string lbl_family {
            get {
                return ResourceManager.GetString("lbl_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 50名以后 的本地化字符串。
        /// </summary>
        internal static string lbl_rank_After50 {
            get {
                return ResourceManager.GetString("lbl_rank_After50", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当前系统时间为 的本地化字符串。
        /// </summary>
        internal static string lbl_rank_curTime {
            get {
                return ResourceManager.GetString("lbl_rank_curTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我 的本地化字符串。
        /// </summary>
        internal static string lbl_rank_me {
            get {
                return ResourceManager.GetString("lbl_rank_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未上榜 的本地化字符串。
        /// </summary>
        internal static string lbl_rank_noRank {
            get {
                return ResourceManager.GetString("lbl_rank_noRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数量 的本地化字符串。
        /// </summary>
        internal static string lbl_rank_num {
            get {
                return ResourceManager.GetString("lbl_rank_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 明星榜统计时间为：每周一00:00到下周日23:59:59 的本地化字符串。
        /// </summary>
        internal static string lbl_rank_tip {
            get {
                return ResourceManager.GetString("lbl_rank_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 周星 的本地化字符串。
        /// </summary>
        internal static string lbl_weekstar {
            get {
                return ResourceManager.GetString("lbl_weekstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 日榜 的本地化字符串。
        /// </summary>
        internal static string tab_rank_day {
            get {
                return ResourceManager.GetString("tab_rank_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 月榜 的本地化字符串。
        /// </summary>
        internal static string tab_rank_month {
            get {
                return ResourceManager.GetString("tab_rank_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 总榜 的本地化字符串。
        /// </summary>
        internal static string tab_rank_total {
            get {
                return ResourceManager.GetString("tab_rank_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 周榜 的本地化字符串。
        /// </summary>
        internal static string tab_rank_weekly {
            get {
                return ResourceManager.GetString("tab_rank_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主播榜 的本地化字符串。
        /// </summary>
        internal static string title_anchor {
            get {
                return ResourceManager.GetString("title_anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 富豪榜 的本地化字符串。
        /// </summary>
        internal static string title_consume {
            get {
                return ResourceManager.GetString("title_consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 家族榜 的本地化字符串。
        /// </summary>
        internal static string title_family {
            get {
                return ResourceManager.GetString("title_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 明星榜 的本地化字符串。
        /// </summary>
        internal static string title_star {
            get {
                return ResourceManager.GetString("title_star", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 粉丝奉献榜 的本地化字符串。
        /// </summary>
        internal static string title_Vermicelli {
            get {
                return ResourceManager.GetString("title_Vermicelli", resourceCulture);
            }
        }
    }
}
